### ISSUE TITLE
Type content_callsheets text

### ISSUE THREAD

**Issue by JudithLco** [Melomania-be/back#20]
Changer text. 
Actuellement ne peut pas dépasser 255char, il faudrait pouvoir mettre davantage d'informations

**Comment by JudithLco** [comment]
Besoin de ce changement aussi pour content_registrations 

error: insert into "content_registrations" ("created_at", "registration_id", "text", "title", "updated_at") values ($1, $2, $3, $4, $5) returning "id" - value too long for type character varying(255)
    at Parser.parseErrorMessage (G:\git\back\node_modules\pg-protocol\src\parser.ts:369:69)
    at Parser.handlePacket (G:\git\back\node_modules\pg-protocol\src\parser.ts:188:21)  
    at Parser.parse (G:\git\back\node_modules\pg-protocol\src\parser.ts:103:30)
    at Socket.<anonymous> (G:\git\back\node_modules\pg-protocol\src\index.ts:7:48)      
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:349:9)
    at Readable.push (node:internal/streams/readable:286:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
